#
# Makefile for the kb drivers.
# insert (/chstime_hr to /drivers, Makefile_prj as Makefile and Kconfig) in to linux-kernel 

# Each configuration option enables a list of files.

obj-$(CONFIG_KSD_MULTI_EVENT) += mod_event_fops_once.o
