#
# Makefile for the kernel serial device drivers.
#

obj-$(CONFIG_SERIAL_SC16IS7XX_I2C_MOD) += sc16is7xx.o
#obj-$(CONFIG_TINY_SERIAL) += mod_tiny_serial.o
obj-$(CONFIG_TINY_TTY) += mod_tiny_tty_mody_thread.o
obj-$(CONFIG_TINY_SERIAL) +=  mod_tiny_tty_mody.o
