#
# Makefile for the kb drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_PVV_DRIVER)	+= mod_pvv_fops.o
obj-$(CONFIG_PVV2_DRIVER)	+= mod_pvv2_fops.o
obj-$(CONFIG_PVV1_DRIVER)	+= mod_pvv1_fops.o

